function varargout=sym_g(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=1;
   return
  case 'nout'
   varargout{1}=1;
   return
  case 'argrange'
   varargout{1}=struct('x',1:3);
   return
  case 'argsize'
   varargout{1}=struct('x',3);
   return
  case 'vector'
   varargout{1}=struct('x',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=1;
order=varargin{1};
f=str2func(sprintf('sym_g_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function out1 = sym_g_rhs_0(in1,in2,in3,in4,in5,in6)
%SYM_G_RHS_0
%    OUT1 = SYM_G_RHS_0(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Aug-2023 01:13:40

out1 = in1./(in2.^2+1.0);
end


function out1 = sym_g_rhs_1(in1,in2,in3,in4,in5,in6)
%SYM_G_RHS_1
%    OUT1 = SYM_G_RHS_1(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Aug-2023 01:13:40

t2 = in2.^2;
t3 = t2+1.0;
out1 = in4./t3-in1.*in2.*in5.*1.0./t3.^2.*2.0;
end


function out1 = sym_g_rhs_2(in1,in2,in3,in4,in5,in6)
%SYM_G_RHS_2
%    OUT1 = SYM_G_RHS_2(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Aug-2023 01:13:40

t2 = in2.^2;
t3 = in5.^2;
t4 = t2+1.0;
t5 = 1.0./t4.^2;
out1 = in1.*t3.*t5.*-2.0-in2.*in4.*in5.*t5.*4.0+in1.*t2.*t3.*1.0./t4.^3.*8.0;
end

