function varargout=sym_mvdP(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=3;
   return
  case 'argrange'
   varargout{1}=struct('x',1:3,'p',4:7);
   return
  case 'argsize'
   varargout{1}=struct('x',3,'p',4);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=3;
order=varargin{1};
f=str2func(sprintf('sym_mvdP_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function [out1,out2,out3] = sym_mvdP_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14)
%sym_mvdP_rhs_0
%    [OUT1,OUT2,OUT3] = sym_mvdP_rhs_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Aug-2023 01:13:39

t2 = -in3;
t3 = 1.0./in5;
t4 = in1+t2;
t5 = t3.*t4;
out1 = -(in2+t5-in7.*(in1-in1.^3./3.0))./in4;
if nargout > 1
    out2 = in1-in6;
end
if nargout > 2
    out3 = t5;
end
end


function [out1,out2,out3] = sym_mvdP_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14)
%sym_mvdP_rhs_1
%    [OUT1,OUT2,OUT3] = sym_mvdP_rhs_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Aug-2023 01:13:39

t2 = in1.^3;
t3 = -in3;
t4 = -in10;
t5 = 1.0./in5;
t6 = t5.^2;
t7 = in1+t3;
t8 = in8+t4;
t9 = t2./3.0;
t10 = -t9;
t12 = t5.*t8;
t13 = in12.*t6.*t7;
t11 = in1+t10;
out1 = (-in9-t12+t13+in7.*(in8-in1.^2.*in8)+in14.*t11)./in4+1.0./in4.^2.*in11.*(in2-in7.*t11+t5.*t7);
if nargout > 1
    out2 = in8-in13;
end
if nargout > 2
    out3 = t12-t13;
end
end


function [out1,out2,out3] = sym_mvdP_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8,in9,in10,in11,in12,in13,in14)
%sym_mvdP_rhs_2
%    [OUT1,OUT2,OUT3] = sym_mvdP_rhs_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10,IN11,IN12,IN13,IN14)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Aug-2023 01:13:39

t2 = in1.^2;
t3 = in1.^3;
t4 = in12.^2;
t5 = -in3;
t6 = -in10;
t7 = 1.0./in5;
t8 = t7.^2;
t9 = t7.^3;
t10 = in8.*t2;
t11 = in1+t5;
t12 = in8+t6;
t13 = t3./3.0;
t14 = -t10;
t15 = -t13;
t18 = in12.*t8.*t12.*2.0;
t19 = t4.*t9.*t11.*2.0;
t16 = in8+t14;
t17 = in1+t15;
out1 = (t18-t19+in14.*t16.*2.0-in1.*in7.*in8.^2.*2.0)./in4-1.0./in4.^2.*in11.*(-in9+in7.*t16+in14.*t17-t7.*t12+in12.*t8.*t11).*2.0-1.0./in4.^3.*in11.^2.*(in2-in7.*t17+t7.*t11).*2.0;
if nargout > 1
    out2 = 0.0;
end
if nargout > 2
    out3 = -t18+t19;
end
end

