function varargout=sym_sphere_obj(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=1;
   return
  case 'nout'
   varargout{1}=1;
   return
  case 'argrange'
   varargout{1}=struct('u',1:4);
   return
  case 'argsize'
   varargout{1}=struct('u',4);
   return
  case 'vector'
   varargout{1}=struct('u',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=2;
   return
end
nout=1;
order=varargin{1};
f=str2func(sprintf('sym_sphere_obj_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});
end



function out1 = sym_sphere_obj_rhs_0(in1,in2,in3,in4,in5,in6,in7,in8)
%SYM_SPHERE_OBJ_RHS_0
%    OUT1 = SYM_SPHERE_OBJ_RHS_0(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Aug-2023 01:11:11

out1 = in1+in2+in3+in4;
end


function out1 = sym_sphere_obj_rhs_1(in1,in2,in3,in4,in5,in6,in7,in8)
%SYM_SPHERE_OBJ_RHS_1
%    OUT1 = SYM_SPHERE_OBJ_RHS_1(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Aug-2023 01:11:11

out1 = in5+in6+in7+in8;
end


function out1 = sym_sphere_obj_rhs_2(in1,in2,in3,in4,in5,in6,in7,in8)
%SYM_SPHERE_OBJ_RHS_2
%    OUT1 = SYM_SPHERE_OBJ_RHS_2(IN1,IN2,IN3,IN4,IN5,IN6,IN7,IN8)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Aug-2023 01:11:11

out1 = 0.0;
end

