function varargout=sys_bykov(action,varargin)
%% Automatically generated with matlabFunction
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'nargs'
   varargout{1}=2;
   return
  case 'nout'
   varargout{1}=3;
   return
  case 'argrange'
   varargout{1}=struct('x',1:3,'p',4:10);
   return
  case 'argsize'
   varargout{1}=struct('x',3,'p',7);
   return
  case 'vector'
   varargout{1}=struct('x',1,'p',1);
   return
  case 'extension'
   varargout{1}='rhs';
   return
  case 'maxorder'
   varargout{1}=3;
   return
end
nout=3;
order=varargin{1};
f=str2func(sprintf('sys_bykov_%s_%d',action,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{2:end});




function [out1,out2,out3] = sys_bykov_rhs_0(x,y,s,Q1,Q2,Q3,Q4,Q5,Q6,K,x_dev,y_dev,s_dev,Q1_dev,Q2_dev,Q3_dev,Q4_dev,Q5_dev,Q6_dev,K_dev)
%SYS_BYKOV_RHS_0
%    [OUT1,OUT2,OUT3] = SYS_BYKOV_RHS_0(X,Y,S,Q1,Q2,Q3,Q4,Q5,Q6,K,X_DEV,Y_DEV,S_DEV,Q1_DEV,Q2_DEV,Q3_DEV,Q4_DEV,Q5_DEV,Q6_DEV,K_DEV)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    26-Jun-2023 06:20:42

t2 = Q3.*x.*y;
t4 = s+x+y-1.0;
t3 = -t2;
out1 = t3+Q1.*t4.^2.*2.0-Q5.*x.^2.*2.0;
if nargout > 1
    out2 = t3-Q2.*t4-Q6.*y;
end
if nargout > 2
    out3 = -Q4.*t4-K.*Q4.*s;
end


function [out1,out2,out3] = sys_bykov_rhs_1(x,y,s,Q1,Q2,Q3,Q4,Q5,Q6,K,x_dev,y_dev,s_dev,Q1_dev,Q2_dev,Q3_dev,Q4_dev,Q5_dev,Q6_dev,K_dev)
%SYS_BYKOV_RHS_1
%    [OUT1,OUT2,OUT3] = SYS_BYKOV_RHS_1(X,Y,S,Q1,Q2,Q3,Q4,Q5,Q6,K,X_DEV,Y_DEV,S_DEV,Q1_DEV,Q2_DEV,Q3_DEV,Q4_DEV,Q5_DEV,Q6_DEV,K_DEV)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    26-Jun-2023 06:20:42

t2 = Q3_dev.*x.*y;
t3 = Q3.*x.*y_dev;
t4 = Q3.*x_dev.*y;
t5 = s_dev+x_dev+y_dev;
t9 = s+x+y-1.0;
t6 = -t2;
t7 = -t3;
t8 = -t4;
out1 = t6+t7+t8+Q1_dev.*t9.^2.*2.0-Q5_dev.*x.^2.*2.0+Q1.*t5.*t9.*4.0-Q5.*x.*x_dev.*4.0;
if nargout > 1
    out2 = t6+t7+t8-Q2.*t5-Q2_dev.*t9-Q6_dev.*y-Q6.*y_dev;
end
if nargout > 2
    out3 = -Q4.*t5-Q4_dev.*t9-K.*Q4_dev.*s-K.*Q4.*s_dev-K_dev.*Q4.*s;
end


function [out1,out2,out3] = sys_bykov_rhs_2(x,y,s,Q1,Q2,Q3,Q4,Q5,Q6,K,x_dev,y_dev,s_dev,Q1_dev,Q2_dev,Q3_dev,Q4_dev,Q5_dev,Q6_dev,K_dev)
%SYS_BYKOV_RHS_2
%    [OUT1,OUT2,OUT3] = SYS_BYKOV_RHS_2(X,Y,S,Q1,Q2,Q3,Q4,Q5,Q6,K,X_DEV,Y_DEV,S_DEV,Q1_DEV,Q2_DEV,Q3_DEV,Q4_DEV,Q5_DEV,Q6_DEV,K_DEV)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    26-Jun-2023 06:20:42

t2 = s_dev+x_dev+y_dev;
t3 = Q3_dev.*x.*y_dev.*2.0;
t4 = Q3_dev.*x_dev.*y.*2.0;
t5 = Q3.*x_dev.*y_dev.*2.0;
t6 = -t3;
t7 = -t4;
t8 = -t5;
out1 = t6+t7+t8+Q1.*t2.^2.*4.0-Q5.*x_dev.^2.*4.0-Q5_dev.*x.*x_dev.*8.0+Q1_dev.*t2.*(s+x+y-1.0).*8.0;
if nargout > 1
    out2 = t6+t7+t8-Q2_dev.*t2.*2.0-Q6_dev.*y_dev.*2.0;
end
if nargout > 2
    out3 = Q4_dev.*t2.*-2.0-K.*Q4_dev.*s_dev.*2.0-K_dev.*Q4_dev.*s.*2.0-K_dev.*Q4.*s_dev.*2.0;
end


function [out1,out2,out3] = sys_bykov_rhs_3(x,y,s,Q1,Q2,Q3,Q4,Q5,Q6,K,x_dev,y_dev,s_dev,Q1_dev,Q2_dev,Q3_dev,Q4_dev,Q5_dev,Q6_dev,K_dev)
%SYS_BYKOV_RHS_3
%    [OUT1,OUT2,OUT3] = SYS_BYKOV_RHS_3(X,Y,S,Q1,Q2,Q3,Q4,Q5,Q6,K,X_DEV,Y_DEV,S_DEV,Q1_DEV,Q2_DEV,Q3_DEV,Q4_DEV,Q5_DEV,Q6_DEV,K_DEV)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    26-Jun-2023 06:20:42

t2 = Q3_dev.*x_dev.*y_dev.*6.0;
t3 = -t2;
out1 = t3-Q5_dev.*x_dev.^2.*1.2e+1+Q1_dev.*(s_dev+x_dev+y_dev).^2.*1.2e+1;
if nargout > 1
    out2 = t3;
end
if nargout > 2
    out3 = K_dev.*Q4_dev.*s_dev.*-6.0;
end

