%--------------------------------------------------------------------
% "Observing hidden neuronal states in experiments" by Amakhin et al.
%  m-file to reproduce Fig.SI1(a)-(d)
%--------------------------------------------------------------------

%% Read processed runs (generated by process_cells1_5.m)
clear 
s=load('../mat_files/processed_runs.mat');
[ccruns,vcruns]=deal(s.ccruns,s.vcruns);
clr=lines();
cm=clr(1,:);
[  cunst,      cund,       cc,          ccslow,    chopf,   cfold]=deal(...
[1,0.2,0.2], [1,0.9,0], [1,0.6,0.4], [1 0.5 0.3], [1,1,1], [0,1,0]);
[cneg,bg]=deal(cunst/2,cm*1/3+2/3);
[shopf,sfold]=deal('s');
[xbd,ybd]=deal([-20,420],[-80,50]);
relcoord=@(bd,frac)bd(1)+frac*diff(bd);
[labelx,labely]=deal(relcoord(xbd,0.02),relcoord(ybd,0.98));
stab_names={...
    'stable','VC stable';...
    'ubyfold','$$\frac{\normalsize\mathrm{d}I_\mathrm{vc}}{\normalsize\mathrm{d}V_\mathrm{h}}<0$$';...
    'undet','VC stability undetermined';...
    'ubyhopf', sprintf('VC unstable by Hopf')}';
stab_struct=struct(stab_names{:});
stab_ic=[stab_names(1,:);num2cell(1:size(stab_names,2))];
stab_ind=struct(stab_ic{:});
stab_cl([stab_ind.stable,stab_ind.ubyhopf,stab_ind.ubyfold,stab_ind.undet])=...
        {          cm,             cunst,          cneg,            cund};
stab_lw([stab_ind.stable,stab_ind.ubyhopf,stab_ind.ubyfold,stab_ind.undet])=...
        {          2,              2,               2,              2};
txt={'FontSize',16,'FontName','Courier','FontWeight','bold'};
ltx=[txt,{'Interpreter','latex'}];
ms={'MarkerSize',8};
%%
fig=figure(2);fig.Name='Figure SI1';clf;tl=tiledlayout(3,2,'TileSpacing','tight');
for i=1:length(ccruns)
    ax(i)=nexttile(tl,i);hold(ax(i),'on');
    [rv,rc]=deal(vcruns(i),ccruns(i));
    ibifs=sort([1;rv.i_fold;rv.i_hopf;length(rv.Is)],'ascend');
    % plot CC run
    pcc=plot(ax(i),rc.Is,rc.V,'LineWidth',1,'color',cc,...
        'DisplayName','$V_\mathrm{cc}(I_\mathrm{h})$');
    % highlight slow parts of CC signal
    pccslow=plot(ax(i),rc.Is,rc.Veq,'LineWidth',1.5,'color',ccslow,'DisplayName','$V_\mathrm{cc}(I_\mathrm{h})$ (slow)');
    % raw data of VC run
    pvcraw=plot(ax(i),rv.I,rv.V,'LineWidth',1,'color',bg,...
        'LineWidth',1,'DisplayName','VC raw');
    % stable parts of VC runs: above depolarization and below first bif
    rg=1:min([rv.i_hopf;rv.i_fold]);
    pstable=plot(ax(i),rv.Is(rg),rv.Vs(rg),'Color',stab_cl{stab_ind.stable},...
        'LineWidth',stab_lw{stab_ind.stable},'DisplayName',stab_struct.stable);
    rg=max([vcruns(i).i_hopf;vcruns(i).i_fold]):length(rv.Is);
    plot(ax(i),rv.Is(rg),rv.Vs(rg),'Color',stab_cl{stab_ind.stable},...
        'LineWidth',stab_lw{stab_ind.stable},'DisplayName',stab_struct.stable);
    % parts of VC run with undetermined stability
    pund=[];
    for k=2:2:length(rv.i_fold)
        rg=adjacent_bif(ibifs,rv.i_fold(k),+1);
        pund=plot(ax(i),rv.Is(rg),rv.Vs(rg),'Color',stab_cl{stab_ind.undet},...
            'LineWidth',stab_lw{stab_ind.undet},'DisplayName',stab_struct.undet);
    end
    % parts of VC run next to Hopf bifurcation
    rg=adjacent_bif(ibifs,rv.i_hopf(1),+1);
    punst=plot(ax(i),rv.Is(rg),rv.Vs(rg),'Color',stab_cl{stab_ind.ubyhopf},...
        'LineWidth',stab_lw{stab_ind.ubyhopf},'DisplayName',stab_struct.ubyhopf);
    rg=adjacent_bif(ibifs,rv.i_hopf(2),-1);
    plot(ax(i),rv.Is(rg),rv.Vs(rg),'Color',stab_cl{stab_ind.ubyhopf},...
        'LineWidth',stab_lw{stab_ind.ubyhopf},'DisplayName',stab_struct.ubyhopf);
    % parts of VC that are unstable for topolgical reasons
    pneg=[];
    for k=1:2:length(rv.i_fold)
        rg=rv.i_fold(k):rv.i_fold(k+1);
        pneg=plot(ax(i),rv.Is(rg),rv.Vs(rg),'Color',stab_cl{stab_ind.ubyfold},...
            'LineWidth',stab_lw{stab_ind.ubyfold},'DisplayName',stab_struct.ubyfold);
    end
    % fold bifurcations
    pfold=plot(ax(i),rv.Is(rv.i_fold),rv.Vs(rv.i_fold),sfold,...
        'Color','k','MarkerFaceColor',cfold,ms{:},...
            'LineWidth',1,'DisplayName','Fold');
    % Hopf bifurcations
    i_hopf=rv.i_hopf;
    [~,i_left]=adjacent_bif(ibifs,i_hopf(1),-1);
    if ismember(i_left,rv.i_fold)
        i_hopf=i_hopf(2:end);
    end
    phopf=plot(ax(i),rv.Is(i_hopf),rv.Vs(i_hopf),shopf,...
        'Color','k','MarkerFaceColor',chopf,ms{:},...
            'LineWidth',1,'DisplayName','Hopf');
    xlim(ax(i),xbd);
    ylim(ax(i),ybd);
    text(ax(i),labelx,labely,sprintf('(%s)',char('a'-1+i)),...
        'HorizontalAlignment','left','VerticalAlignment','top',ltx{:});
    set(ax(i),txt{:},'box','on')
    if mod(i,2)==0
        ax(i).YTickLabel={' '};
    else
        ylabel(ax(i),'$V_\mathrm{h}\approx V,\;V_\mathrm{cc}$ (mV)',ltx{:});
    end
    xlabel(ax(i),'$I_\mathrm{vc},\;I_\mathrm{h}$\,(pA)',ltx{:});
end
lg=legend([pcc,pccslow,pvcraw,pstable,pneg,punst,pund,pfold,phopf],ltx{:});
lg.Layout.Tile=6;
fig.Position(3:4)=[900,850];
%%
fig.Color='w';
exportgraphics(fig,'../figures/FigureSI1.pdf','ContentType','vector');
%%% Plot CC after smoothing

function [rg,i_adj]=adjacent_bif(ibifs,ibifcur,pm)
icur=find(ibifs==ibifcur);
i_adj=ibifs(icur+pm*1);
rg=ibifcur:pm:i_adj;
end